import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import {
  Atkinson_Hyperlegible_Mono,
  Lexend,
  Merriweather,
} from "next/font/google";

import { I18nProvider } from "@/app/providers";
import { Header } from "@/components/header";
import {
  COLOR_SCHEME_COOKIE,
  COLOR_SCHEME_HEADER,
  FONT_FAMILY_COOKIE,
  FONT_FAMILY_HEADER,
  TEXT_SIZE_COOKIE,
  TEXT_SIZE_HEADER,
  normalizeColorScheme,
  normalizeFontFamily,
  normalizeTextSize,
} from "@/lib/a11y-preferences";
import { LOCALE_COOKIE, LOCALE_HEADER } from "@/i18n/config";
import { normalizeLocale } from "@/lib/resolve-locale";

import "./globals.css";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const atkinsonMono = Atkinson_Hyperlegible_Mono({
  variable: "--font-atkinson-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerStore = await headers();
  const cookieStore = await cookies();
  const locale = normalizeLocale(
    headerStore.get(LOCALE_HEADER) ?? cookieStore.get(LOCALE_COOKIE)?.value,
  );

  const colorScheme = normalizeColorScheme(
    headerStore.get(COLOR_SCHEME_HEADER) ??
      cookieStore.get(COLOR_SCHEME_COOKIE)?.value,
  );
  const fontFamily = normalizeFontFamily(
    headerStore.get(FONT_FAMILY_HEADER) ??
      cookieStore.get(FONT_FAMILY_COOKIE)?.value,
  );
  const textSize = normalizeTextSize(
    headerStore.get(TEXT_SIZE_HEADER) ??
      cookieStore.get(TEXT_SIZE_COOKIE)?.value,
  );

  return (
    <html
      lang={locale}
      data-color-scheme={colorScheme}
      data-font={fontFamily}
      data-text-size={textSize === "large" ? "large" : undefined}
      className={`${atkinsonMono.variable} ${lexend.variable} ${merriweather.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-background text-foreground">
        <I18nProvider locale={locale}>
          <Header
            initialColorScheme={colorScheme}
            initialFontFamily={fontFamily}
            initialTextSize={textSize}
          />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
