import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import {
  Atkinson_Hyperlegible_Mono,
  Lexend,
  Merriweather,
} from "next/font/google";

import { I18nProvider } from "@/app/providers";
import { LOCALE_COOKIE, LOCALE_HEADER } from "@/i18n/config";
import { normalizeLocale } from "@/lib/resolve-locale";

import "./globals.css";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const atkinsonMono = Atkinson_Hyperlegible_Mono({
  variable: "--font-atkinson-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerStore = await headers();
  const cookieStore = await cookies();
  const locale = normalizeLocale(
    headerStore.get(LOCALE_HEADER) ?? cookieStore.get(LOCALE_COOKIE)?.value,
  );

  return (
    <html
      lang={locale}
      className={`${atkinsonMono.variable} ${lexend.variable} ${merriweather.variable} h-full antialiased`}
    >
      <body className="font-mono flex min-h-full flex-col bg-background text-foreground">
        <I18nProvider locale={locale}>{children}</I18nProvider>
      </body>
    </html>
  );
}
